FROM alpine:latest
RUN apk add --update rebar3 build-base bsd-compat-headers curl nodejs npm inotify-tools
RUN apk add \
  --no-cache \
  --repository=https://dl-cdn.alpinelinux.org/alpine/edge/community \
  gleam=~1.3
COPY ./frontend /app
COPY ./shared /shared
WORKDIR /app
RUN gleam clean
RUN sh env.sh http://localhost:1234
RUN gleam clean
CMD ["gleam", "run", "-m", "lustre/dev", "start", "--proxy-from=/api", "--proxy-to=http://backend:8001/"]
