services:
  mysql:
    image: mysql
    restart: always
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: kirakira
      MYSQL_PASSWORD: kirakira
      MYSQL_USER: kirakira
      MYSQL_DATABASE: kirakira
    volumes:
      - mysql:/var/lib/mysql
  phpmyadmin:
    image: phpmyadmin
    restart: always
    ports:
      - 8080:80
    environment:
      - PMA_ARBITRARY=1
      - PMA_PORT=3306
      - PMA_HOST=mysql
      - PMA_USER=root
      - PMA_PASSWORD=kirakira
  client:
    build:
      context: .
      dockerfile: ./client/Dockerfile.dev
    ports:
      - "1234:1234"
    volumes:
      - type: bind
        source: ./client
        target: /app
      - type: bind
        source: ./shared
        target: /shared
  server:
    build:
      context: .
      dockerfile: ./server/Dockerfile.dev
    ports:
      - "8001:8001"
    volumes:
      - type: bind
        source: ./server
        target: /app
      - type: bind
        source: ./shared
        target: /shared
      - type: bind
        source: ./gmysql
        target: /gmysql
volumes:
  mysql: ~
  dev:
