services:
  frontend:
    build:
      context: .
      dockerfile: ./frontend/Dockerfile
    ports:
      - '1234:1234'
  backend: 
    build:
      context: .
      dockerfile: ./backend/Dockerfile
    ports:
      - '8001:8001'
volumes:
  mysql: ~
  dev:
