FROM ghcr.io/gleam-lang/gleam:v1.11.0-erlang-alpine
RUN apk add rebar3 build-base bsd-compat-headers inotify-tools
COPY ./ /app
WORKDIR /app/client
RUN echo "pub fn get_api_url() { \"https://kirakira.keii.dev\" }" > ./src/env.gleam
RUN gleam run -m lustre/dev build --outdir=../server/priv/static --minify
WORKDIR /app/server
CMD gleam run
