services:
  mysql:
    image: mysql
    restart: always
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: kirakira
      MYSQL_PASSWORD: kirakira
      MYSQL_USER: kirakira
      MYSQL_DATABASE: kirakira
    volumes:
      - mysql:/var/lib/mysql
  phpmyadmin:
    image: phpmyadmin
    restart: always
    ports:
      - 8080:80
    environment:
      - PMA_ARBITRARY=1
      - PMA_PORT=3306
      - PMA_HOST=mysql
      - PMA_USER=root
      - PMA_PASSWORD=kirakira
  frontend-dev:
    build:
      context: .
      dockerfile: ./frontend/Dockerfile
    ports:
      - '1234:1234'
    volumes:
      - type: bind
        source: ./frontend
        target: /app
  frontend-prod:
    build:
      context: .
      dockerfile: ./frontend/Dockerfile
    ports:
      - '1234:1234'
  backend: 
    environment:
      - DB_HOST=mysql
    build:
      context: .
      dockerfile: ./backend/Dockerfile
    ports:
      - '8001:8001'
volumes:
  mysql: ~
  dev:
