FROM alpine:latest
RUN apk add \
    --no-cache \
    --repository=https://dl-cdn.alpinelinux.org/alpine/edge/community \
    gleam=~1.6
RUN apk add rebar3 build-base bsd-compat-headers curl watchexec just
COPY ./ /app
WORKDIR /app
ENV DB_HOST postgres
ENV DB_PASSWORD kirakira
ENV DB_USER root
ENV DB_NAME kirakira
ENV DB_PORT 3306
RUN just clean
CMD ["watchexec", "-r", "-e", "gleam", "--", "just", "dev-no-env"]
