FROM alpine:latest
RUN apk add \
  --no-cache \
  --repository=https://dl-cdn.alpinelinux.org/alpine/edge/community \
  gleam=~1.3
RUN apk add rebar3 build-base bsd-compat-headers curl watchexec
COPY ./server /app
COPY ./gmysql /gmysql
COPY ./shared /shared
WORKDIR /app
ENV DB_HOST mysql 
ENV DB_PASSWORD kirakira 
ENV DB_USER root 
ENV DB_NAME kirakira 
ENV DB_PORT 3306
CMD ["watchexec", "-r", "-e", "gleam", "--", "gleam", "run"]
