name = "server"
version = "1.0.0"

# Fill out these fields if you intend to generate HTML documentation or publish
# your project to the Hex package manager.
#
# description = ""
# licences = ["Apache-2.0"]
# repository = { type = "github", user = "", repo = "" }
# links = [{ title = "Website", href = "" }]
#
# For a full reference of all the available options, you can have a look at
# https://gleam.run/writing-gleam/gleam-toml/.

[dependencies]
shared = { path = "../shared" }
beecrypt = ">= 0.3.1 and < 1.0.0"
gleam_http = ">= 4.0.0 and < 5.0.0"
glenv = ">= 0.4.0 and < 1.0.0"
client = { path = "../client" }
lustre = ">= 5.0.0 and < 6.0.0"
xmleam = ">= 1.2.0 and < 2.0.0"
gleesend = ">= 2.0.2 and < 3.0.0"
webls = ">= 1.4.0 and < 2.0.0"
gleam_erlang = ">= 0.25.0 and < 1.0.0"
wisp = ">= 1.4.0 and < 2.0.0"
prng = ">= 4.0.0 and < 5.0.0"
gleam_stdlib = ">= 0.48.0 and < 1.0.0"
gleam_json = ">= 3.0.0 and < 4.0.0"
gleam_httpc = ">= 4.0.0 and < 5.0.0"
gleam_regexp = ">= 1.0.0 and < 2.0.0"
birl = ">= 1.8.0 and < 2.0.0"
mist = ">= 4.0.0 and < 5.0.0"
cors_builder = ">= 2.0.3 and < 3.0.0"
glisten = ">= 7.0.0 and < 8.0.0"
simplifile = ">= 2.2.0 and < 3.0.0"
parrot = ">= 1.0.1 and < 2.0.0"
shork = ">= 1.2.0 and < 2.0.0"
dot_env = ">= 1.2.0 and < 2.0.0"

[dev-dependencies]
gleeunit = ">= 1.0.0 and < 2.0.0"
