name = "server"
version = "1.0.0"

# Fill out these fields if you intend to generate HTML documentation or publish
# your project to the Hex package manager.
#
# description = ""
# licences = ["Apache-2.0"]
# repository = { type = "github", user = "", repo = "" }
# links = [{ title = "Website", href = "" }]
#
# For a full reference of all the available options, you can have a look at
# https://gleam.run/writing-gleam/gleam-toml/.

[dependencies]
shared = { path = "../shared" }
beecrypt = ">= 0.3.1 and < 1.0.0"
gleam_http = ">= 3.6.0 and < 4.0.0"
glenv = ">= 0.4.0 and < 1.0.0"
client = { path = "../client" }
lustre = ">= 4.3.1 and < 5.0.0"
xmleam = { path = "../xmleam" }
gleesend = ">= 2.0.2 and < 3.0.0"
webls = ">= 1.4.0 and < 2.0.0"
wisp = { path = "../wisp" }
gleam_erlang = ">= 0.25.0 and < 1.0.0"
prng = ">= 3.0.3 and < 4.0.0"
# cors_builder = ">= 2.0.0 and < 3.0.0"
decode = ">= 0.3.0 and < 1.0.0"
birl = { path = "../birl" }
cors_builder = { path = "../cors-builder" }
# gramps = { path = "../gramps" }
mist = { path = "../mist" }
gleam_stdlib = ">= 0.48.0 and < 1.0.0"
gleam_json = ">= 2.0.0 and < 3.0.0"
pog = ">= 1.1.0 and < 2.0.0"
gleam_httpc = ">= 4.0.0 and < 5.0.0"
gleam_regexp = ">= 1.0.0 and < 2.0.0"


[dev-dependencies]
gleeunit = ">= 1.0.0 and < 2.0.0"
squirrel = ">= 2.0.0 and < 3.0.0"
